name: cyclic_alarm_clock
description: A cyclic alarm clock with shuffled daily playlist for Android.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  android_alarm_manager_plus: ^3.0.3
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.12
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
